# See https://github.com/AFLplusplus/AFLplusplus/blob/stable/docs/rpc_statsd.md#installing-and-setting-up-statsd-prometheus-and-grafana
global:
  scrape_interval:      15s
  evaluation_interval:  15s

scrape_configs:
  - job_name: 'fuzzing_metrics'
    static_configs:
      - targets: ['statsd_exporter:9102']